########################################################################
#                                                                      #
#                                                                      #
#                 EpiphanyMC Staff Auth Plugin                         #
#   Created by Ambedo Services CEO Phil K. aka Lead Dev DopeDealers    #
#                                                                      #
#                                                                      #
########################################################################

########################################################################
#                                                                      #
#                                                                      #
#                 EpiphanyMC Staff Auth Plugin                         #
#   Created by Ambedo Services CEO Phil K. aka Lead Dev DopeDealers    #
#                                                                      #
#                                                                      #
########################################################################


########################################
#                                      #
# Customizable Messages for the plugin #
#                                      #
########################################
messages:
  prefix: '&8[&4&lEpiphanyMC&8-&b&lStaffAuth&8]'
  login-setup: '%prefix% &cYour &bGoogle Setup Code&c is &6&l%key%'
  login-join: '&cPlease open the Google Authenticator App and provide the six digit code.'
  access-granted: '%prefix% &aAccess Granted.'
  NoPerm: "&cYou do not have permission to do this.."
  Reload: "&aReload Successful!"
  EpiphanyInfo:
  - '&8&m----------------------'
  - ''
  - '&4&l   EpiphanyMC&8-&b&lStaffAuth'
  - ''
  - '&cCommands:'
  - '&7/staffauth | Shows this'
  - '&7/staffauth reload | Admin Only'
  - '&7/staffauth version | Shows info'
  - ''
  - '&8&m----------------------'

#####################################################################
#                                                                   #
# Every Staffs UUID and Google Code Setup WILL be logged under here #
#                                                                   #
#                                                                   #
# Example                                                           #
# authcodes:                                                        #
#   uuid: code                                                      #
#                                                                   #
# Deleting this code from the user will result                      #
# in them not being able to join.                                   #
#                                                                   #
#####################################################################
